### ISSUE TITLE
RuntimeError: Missing setup required dependencies: cppy. 

### ISSUE THREAD

**Issue by zaheerkzz** [nucleic/cppy#25]
python version 3.9
cppy==1.2.1
setuptools==65.3.0

I already have installed cppy version 1.2.1
here is the error while building kiwisolver using buildozer.

```
RuntimeError: Missing setup required dependencies: cppy. Installing through pip as recommended ensure one never hits this issue.
```

here is the complete log. I tried searching but no answers found. 

```
[DEBUG]:   -> running python3 setup.py build_ext -v
[DEBUG]:        Traceback (most recent call last):
[DEBUG]:          File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a_x86_x86_64/build/other_builds/kiwisolver/x86__ndk_target_21/kiwisolver/setup.py", line 13, in <module>
[DEBUG]:            from cppy import CppyBuildExt
[DEBUG]:          File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a_x86_x86_64/build/other_builds/hostpython3/desktop/hostpython3/native-build/Lib/site-packages/cppy/__init__.py", line 13, in <module>
[DEBUG]:            from .version import __version__, __version_info__
[DEBUG]:        ModuleNotFoundError: No module named 'cppy.version'
[DEBUG]:   
[DEBUG]:        The above exception was the direct cause of the following exception:
[DEBUG]:   
[DEBUG]:        Traceback (most recent call last):
[DEBUG]:          File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a_x86_x86_64/build/other_builds/kiwisolver/x86__ndk_target_21/kiwisolver/setup.py", line 15, in <module>
[DEBUG]:            raise RuntimeError(
[DEBUG]:        RuntimeError: Missing setup required dependencies: cppy. Installing through pip as recommended ensure one never hits this issue.
Exception in thread background thread for pid 278125:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zaheer/.local/share/virtualenvs/KivyAnd3.9v-wH4pEdLB/lib/python3.9/site-packages/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/home/zaheer/.local/share/virtualenvs/KivyAnd3.9v-wH4pEdLB/lib/python3.9/site-packages/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/home/zaheer/.local/share/virtualenvs/KivyAnd3.9v-wH4pEdLB/lib/python3.9/site-packages/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/zaheer/.local/share/virtualenvs/KivyAnd3.9v-wH4pEdLB/lib/python3.9/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a_x86_x86_64/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v

  STDOUT:
Traceback (most recent call last):
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a_x86_x86_64/build/other_builds/kiwisolver/x86__ndk_target_21/kiwisolver/setup.py", line 13, in <module>
    from cppy import CppyBuildExt
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a_x86_x86_64/build/other_builds/hostpython3/desktop/hostpython3/native-build/Lib/site-packages/cppy/__init__.py", line 13, in <module>
    from .version import __version__, __version_info__
ModuleNotFoundError: No module named 'cppy.version'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a_x86_x86_64/build/other_builds/kiwisolver/x86__ndk_target_21/kiwisolver/setup.py", line 15, in <module>
    raise RuntimeError(
RuntimeError: Missing setup required dependencies: cppy. Installing through pip as recommended ensure one never hits this issue.


  STDERR:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1297, in <module>
    main()
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 730, in __init__
    getattr(self, command)(args)
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 212, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 505, in build_recipes
    recipe.build_arch(arch)
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 981, in build_arch
    self.build_compiled_components(arch)
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 992, in build_compiled_components
    shprint(hostpython, 'setup.py', self.build_cmd, '-v',
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/home/zaheer/.local/share/virtualenvs/KivyAnd3.9v-wH4pEdLB/lib/python3.9/site-packages/sh.py", line 915, in next
    self.wait()
  File "/home/zaheer/.local/share/virtualenvs/KivyAnd3.9v-wH4pEdLB/lib/python3.9/site-packages/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/zaheer/.local/share/virtualenvs/KivyAnd3.9v-wH4pEdLB/lib/python3.9/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a_x86_x86_64/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v

  STDOUT:
Traceback (most recent call last):
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a_x86_x86_64/build/other_builds/kiwisolver/x86__ndk_target_21/kiwisolver/setup.py", line 13, in <module>
    from cppy import CppyBuildExt
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a_x86_x86_64/build/other_builds/hostpython3/desktop/hostpython3/native-build/Lib/site-packages/cppy/__init__.py", line 13, in <module>
    from .version import __version__, __version_info__
ModuleNotFoundError: No module named 'cppy.version'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zaheer/Desktop/KivyAnd3.9v/gribplot/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a_x86_x86_64/build/other_builds/kiwisolver/x86__ndk_target_21/kiwisolver/setup.py", line 15, in <module>
    raise RuntimeError(
RuntimeError: Missing setup required dependencies: cppy. Installing through pip as recommended ensure one never hits this issue.


  STDERR:

```

**Comment by MatthieuDartiailh** [comment]
As mentioned in the error report, kiwisolver relies on PEP517 and as a consequence should not be built by running setup.py. One should either use pip (or build at a lower level) to build the package.

**Comment by MatthieuDartiailh** [comment]
Feel free to close if this addresses your issue
